- Computer Organisation and Architecture/InstructionSetArchitecture.md
- Computer Organisation and Architecture/MemoryAddressing.md
- Contributors List/TGFlame.md
Please let me know if there are any corrections required
> Added COA folder and updated Contributors list

- Contributors List/theDreamer911.md
- Machine Learning/deep-learning.md
I see that deep learning is not yet exist so it probably can be added, thanks
> adding deep learning resources

- Contributors List/Chitrakshi2531.md
- Contributors List/README.md
for pull request created folder for normalization
> Added details in contributors list

- React/1. Intro.md
- React/2. Setting Up React.md
- React/3. Modifying React Application.md
- React/4. ES6.md
- React/5. React Render.md
- React/6. React JSX.md
- React/7. React Components.md
I will also continue to add more and more files to the folder.
> Added React.js for beginners to learn

- Computer Network & Security/Information Security.md
There is a very basic topic in computer networks and security, it's information security, so I adding it.
> Create Information Security.md

- Computer Network & Security/Threat_Actor.md
the threat actor is a deeper concept in information security
> adding threat actor information

- Python/Python Projects For Beginners
- README.md
I have added 3 Python Projects for beginners. The process of the project and what are the packages should be installed are mentioned in the file clearly.
> Created Python projects for Beginners

- CONTRIBUTING.md
- Contributors List/README.md
- Contributors List/SreeHaran.md
- Data Structures and Algorithms/Tim-Sort.md
- README.md
Hi, I have added the Tim sort algorithm and fixed some typos in readme.md and contributing.md files.
> Added Tim Sort Algorithm

- Contributors List/README.md
- Contributors List/ShashvatJain.md
- Operating System/Scheduling Algorithm (SJF).md
- README.md
Hi, I have added the Scheduling Algorithm and Shortest Job First Algorithm and changed the readMe.md and contributing.md.
> Added Scheduling Algorithm (SJF)

- OOPs/oops-basics.md
I have created a new folder called OOPs in which i have added the concepts of oops along with some example codes.
Please review and suggest any changes.
> Adding Object Oriented Programming with reference to issue #93

- Cloud/Cloud-Computing.md
Create cloud folder and added cloud computing readme file and resources in that.
> added Cloud computing readme file

- CONTRIBUTING.md
- Operating System/Round Robin Scheduling Algorithm.md
Hi, I have added Scheduling Algorithms along with Round Robin Scheduling Algorithm and its code. I request you to add the hacktoberfest-accepted tag.
> Added Round Robin Algorithm

- Computer Program Games/tic_tac_toe.py
I have been assigned issue #123 so here is the code file. Please review and merge it. THANKS!!
> added tic tac toe (issue #123)

- Computer Network & Security/cryptographic_concept.md
Adding the concept of cryptography that implement in computer security
> Create the cryptographic_concepts.md

- Python/rock_pape_scissors.py
rock paper scissors game in python
> rock_paper_scissors.py

- CONTRIBUTING.md
- Operating System/Priority Scheduling.md
Hi, I have added Scheduling Algorithms along with Priority Scheduling and its code. I request you to add the hacktoberfest-accepted tag.
> Added Priority Scheduling

- Contributors List/Avni Arora.md
- Data Structures and Algorithms/two_pointer_technique.md
Two pointers is really an easy and effective technique that is typically used for searching pairs in a sorted array.
Given a sorted array A (sorted in ascending order), having N integers, find if there exists any pair of elements (A[i], A[j]) such that their sum is equal to X.
> Added Two pointer Technique Algorithm

- Contributors List/Hariom.md
Added my name in contributor list.
> Created Hariom.md

- Contributors List/Ritik Kumar.md
- Data Structures and Algorithms/Segment Tree/Explanation.txt
- Data Structures and Algorithms/Segment Tree/Range_minimum_query.cpp
- Data Structures and Algorithms/Segment Tree/Range_sum_query.cpp
I've added segment tree portion like Range Sum Query and Range Minimum Query here kindly consider it and add it as contribution in hacktoberfest2022.
> Added segment tree

- C++/cpp.md
- Contributors List/adityaajay29.md
Hi, 
I have created a new folder named C++, and created a markdown file for all the basic concepts, syntax and STL of c++ language. Please review it.
Thanks!
> Adding C++ basics and syntax with reference to issue #138

- Contributors List/mayank.md
- Euclid_algo/gcd.cpp
> added euclid  algo

- DBMS/Normalization/readme.md
> updated advantages

- CONTRIBUTING.md
- Operating System/First Come First Serve Algorithm.md
Hi, I have added the Scheduling Algorithm and First Come First Serve Algorithm and changed the readMe.md and contributing.md. I request you to merge this commit and add the hacktoberfest-accepted tag.
Thanks !
> Added First Come First Serve Algorithm

- C++/[feature: Added Game to Guess Numbers]
[feature: Added Game to Guess Numbers in C++ Language]
> Create [feature: Added Game to Guess Numbers]

- C++/digitalclock.cpp
> digital clock

- Operating System/Threads_and_Concurrency.md
Hi @its-red-eagle I have added Threads and Concurrency topic in Operating system folder. Please take a look.
> Done some changes in Operating System folder

- Java/javaAsLanguage.md
Hi @its-red-eagle I have added javaAsLanguage.md file in Java folder. Please take a look.
> Updated Java folder 

- Computer Network & Security/Interview_Questions.md
Hi @its-red-eagle I have added interview questions of networking subject. Please take a look.
> Updated computer networking folder added some content

- React/react_best_practices.md
Hi @its-red-eagle I have added file which consists of best practices used in React. Please take a look.
> Added best practices for writing React

- SQL/sql_interview_questions.md
Hi @its-red-eagle I have added some sql interview questions and answers. Please take a look.
> Added some sql content

- Machine Learning/computer_vision_interview.md
Hi @its-red-eagle I have added computer vision interview problems. Please take a look.
> Updated Machine learning folder

- Python/python_interview_questions.md
Hi @its-red-eagle I have added python interview questions and answers. Please take a look.
> Added files in python folder to update it

- Data Structures and Algorithms/Graph/Bipartite_graph.cpp
- Data Structures and Algorithms/Graph/Dense_Graph_vs_Sparse_graph.txt
- Data Structures and Algorithms/Graph/Maximum_Diameter_in_N_ary_tree.cpp.cpp
- Data Structures and Algorithms/Graph/Robber_&_you.cpp
- Data Structures and Algorithms/Graph/Rotten_Oranges_(Multisource_BFS).cpp
- Data Structures and Algorithms/Graph/Simple_Prim's.cpp.txt
- Data Structures and Algorithms/Graph/Standard Algos/Dijiktra's_Algo.cpp
- Data Structures and Algorithms/Graph/Standard Algos/Disjoint_set.cpp
- Data Structures and Algorithms/Graph/Standard Algos/Graph_Articulation_point_and_Bridges.cpp
- Data Structures and Algorithms/Graph/Standard Algos/Kahn's_Algo_(Topological_sort_BFS).cpp
- Data Structures and Algorithms/Graph/Standard Algos/Kosaraju_SCC(Strongly_Connected_Components).cpp
- Data Structures and Algorithms/Graph/Standard Algos/Kruskal_algo.cpp.txt
- Data Structures and Algorithms/Graph/Standard Algos/Prim's_Algorithm.cpp
- Data Structures and Algorithms/Graph/Standard Algos/Prim's_algo.cpp.txt
- Data Structures and Algorithms/Graph/Standard Algos/floyd_Warshell.cpp
- Data Structures and Algorithms/Graph/Topological_sort_DFS.cpp.txt
- Data Structures and Algorithms/Graph/labyrinth_cses_graph.cpp
- Data Structures and Algorithms/Graph/round_trip.cpp
- Data Structures and Algorithms/Graph/sum_from_each_node_to_each_node.cpp
1. Prim's algo
2. Kruskal algo
3. Kosaraju algo
4. Kahn's algo
5. Dijikstra algo
6. Floyd Warshell alfo
7. Disjoint Set algo
8. Topological sort algo
9. Graph Articulation point and Bridges alfo
10. Check Bipartite graph
11. Rotten oranges(Multisource BFS)
> Added All Standard Graph Algos and some questions

- Ai/Ai.md
> Added About AI
